=== Azure/azure-devtestlab/schemas/2015-01-01/dtlArtifacts.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "http://schema.management.azure.com/schemas/2015-01-01/dtlArtifacts.json",
    "type": "object",
    "required": [ "title", "description", "targetOsType" ],
    "oneOf": [
        {
            "required": [ "runAzureVMExtension" ]
        },
        {
            "required": [ "runCommand" ]
        }
    ],
    "properties": {
        "title": {
            "type": "string",
            "description": "The title of your artifact."
        },
        "description": {
            "type": "string",
            "description": "The description of your artifact."
        },
        "iconUri": {
            "type": "string"
        },
        "tags": {
            "type": "array",
            "items": [
                {
                    "type": "string"
                }
            ]
        },
        "targetOsType": {
            "type": "string",
            "enum": [ "Windows", "Linux" ]
        },
        "runAzureVMExtension": {
            "type": "object",
            "properties": {
            }
        },
        "runCommand": {
            "type": "object",
            "required": [ "commandToExecute" ],
            "properties": {
                "commandToExecute": {
                    "type": "string",
                    "description": "Command to run"
                }
            },
            "additionalProperties": false
        },
        "parameters": {
            "type": "object",
            "description": "Input parameter definitions",
            "additionalProperties": {
                "$ref": "#/definitions/parameter"
            }
        }
    },
    "definitions": {
        "parameter": {
            "type": "object",
            "required": [ "type" ],
            "properties": {
                "type": {
                    "$ref": "#/definitions/parameterTypes",
                    "description": "Type of input parameter"
                },
                "controlType": {
                    "$ref": "#/definitions/controlTypes",
                    "description": "Type of UI control"
                },
                "defaultValue": {
                    "$ref": "#/definitions/parameterValueTypes",
                    "description": "Default value to be used if one is not provided"
                },
                "allowedValues": {
                    "type": "array",
                    "description": "Value can only be one of these values"
                },
                "minLength": {
                    "type": "integer",
                    "description": "Minimum number of characters that must be used"
                },
                "maxLength": {
                    "type": "integer",
                    "description": "Maximum number of characters that can be used"
                },
                "allowEmpty": {
                    "type": "boolean",
                    "description": "If an empty value is allowed, by default false"
                },
                "description": {
                    "type": "string",
                    "description": "The description of the parameter"
                },
                "displayName": {
                    "type": "string",
                    "description": "The display name of the parameter"
                }
            },
            "description": "Input parameter definitions"
        },
        "parameterTypes": {
            "enum": [
                "string",
                "securestring",
                "int",
                "bool",
                "object",
                "array"
            ]
        },
        "controlTypes": {
            "enum": [
                "textBox",
                "passwordBox",
                "fileContents"
            ]
        },
        "parameterValueTypes": {
            "type": [
                "string",
                "boolean",
                "integer",
                "number",
                "object",
                "array",
                "null"
            ]
        }
    }
}

=== Azure/azure-devtestlab/Artifacts/windows-sharepoint2013D/Artifactfile.json
{
  "$schema": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/schemas/2015-01-01/dtlArtifacts.json",
  "title": "SharePoint Server 2013 (4) SP1 Configure Shell VM",
  "description": "Configure SharePoint Server 2013 SP1.",
  "tags": [
    "Windows"
  ],
  "iconUri": "https://i-msdn.sec.s-msft.com/dynimg/IC792065.jpg",
  "targetOsType": "Windows",
    "parameters": {
    "USER": {
      "type": "string",
      "displayName": "User Name",
      "description": "Domain and User"
    }
  },
  "runCommand": {
    "commandToExecute": "[concat('powershell.exe -ExecutionPolicy bypass -File SharePoint2013SP1ConfigureBase.ps1', ' -USER ', parameters('USER'))]"
  }
}

=== Azure/azure-devtestlab/Artifacts/linux-change-password/Artifactfile.json
{
    "$schema": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/schemas/2016-11-28/dtlArtifacts.json",
    "title": "Reset VM Password",
    "description": "Uses the VMAccess extension to reset the built-in administrator account.",
    "tags": [
        "Linux"
    ],
    "targetOsType": "Linux",
    "parameters": {
        "userName": {
            "type": "string",
            "displayName": "User name",
            "description": "The user account to reset."
        },
        "password": {
            "type": "securestring",
            "displayName": "Password",
            "description": "New password for the user name"
        },
        "sshReset": {
            "type": "bool",
            "defaultValue": false,
            "allowedValues": [
                true,
                false
            ],
            "metadata" : {
                "description":"Whether or not reset the ssh."
            }
        }
    },
    "runAzureVMExtension": {
        "publisher": "Microsoft.OSTCExtensions",
        "type": "VMAccessForLinux",
        "typeHandlerVersion": "1.4",
        "autoUpgradeMinorVersion": true,
        "protectedSettings": {
            "username": "[parameters('userName')]",
            "password": "[parameters('password')]",
            "reset_ssh": "[parameters('sshReset')]"
        }
    }
}

=== Azure/azure-devtestlab/Artifacts/windows-gvim-cream/Artifactfile.json
{
  "$schema": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/schemas/2016-11-28/dtlArtifacts.json",
  "title": "gVim (Cream) for Windows",
  "description": "Installs gVim for Windows, with the Cream superset of functionality added. You can view the current status of the Cream project here: http://cream.sourceforge.net/. The application is installed to the default location and should show up in the recently installed list for all users on the VM (depending on the quantity of software being installed prior to logging in). Vim is not installed in such a way as to be made available on the system path.",
  "tags": [
    "Windows",
    "gVim",
    "vim",
    "Editors"
  ],
  "iconUri": "https://github.com/Azure/azure-devtestlab/raw/master/Artifacts/windows-gvim-cream/vim.ico",
  "parameters": {
  "VimInstallerPath": {
    "type": "string",
    "displayName": "Installer Path",
    "description": "The full path to the installer file on the local VM. This should be a full path specification including the file name itself.",
    "defaultValue": "C:\\Temp\\gvim.exe"
    }
  },
  "targetOsType": "Windows",
  "runCommand": {
    "commandToExecute": "[concat('powershell.exe -ExecutionPolicy bypass -File Install-gVim.ps1', ' -VimInstallerPath ', parameters('VimInstallerPath'))]"
  }
}

=== Azure/azure-devtestlab/Artifacts/linux-npm-package/Artifactfile.json
{
    "$schema": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/schemas/2015-01-01/dtlArtifacts.json",
    "title": "NPM Package",
    "description": "Install NPM packages on linux using the Node Package Manager.",
    "tags": [
        "NPM",
        "Linux",
        "Packages"
    ],
    "iconUri": "https://www.npmjs.com/favicon.ico",
    "targetOsType": "Linux",
    "parameters": {
        "installLocation": {
            "type": "string",
            "displayName": "Install Location",
            "defaultValue": "/var/tmp",
            "allowEmpty": false,
            "description": "The local path to install the package to or the keyword 'global' to install the package(s) globally instead."
        },
        "packages": {
            "type": "string",
            "displayName": "Packages to Install",
            "description": "The package names you wish to have installed via NPM, separated by commas. The packages will be installed globally. If NPM is not yet on the system, it also will be installed. You can find NPM package names in the index found at https://www.npmjs.com. All npm install commands are supported, however if a git/bitbucket/gist scope is given then you must have installed the git artifact prior to this npm package artifact."
        },
        "otherOptions": {
            "type": "string",
            "displayName": "Additional Options",
            "allowEmpty": true,
            "defaultValue": "",
            "description": "Any additional options you wish to supply on the command line. See npm install man page here: https://docs.npmjs.com/cli/install"
        }
    },
    "runCommand": {
      "commandToExecute": "[concat('sh linux-npm-package.sh', ' --packages ', parameters('packages'), ' --install-to ', parameters('installLocation'), ' --options ', parameters('otherOptions'))]"
  }
}

=== Azure/azure-devtestlab/Artifacts/windows-sublime-text/Artifactfile.json
{
    "$schema": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/schemas/2015-01-01/dtlArtifacts.json",
    "title": "Sublime Text",
    "description": "Installs SublimeText using the Chocolatey package manager",
    "tags": [
        "Windows",
        "SublimeText"
    ],
    "iconUri": "https://chocolatey.org/content/packageimages/SublimeText3.PackageControl.2.0.0.20140915.png",
    "targetOsType": "Windows",
    "runCommand": {
        "commandToExecute": "powershell.exe -ExecutionPolicy bypass -File startChocolatey.ps1 -PackageList sublimetext3"
    }
}

=== Azure/azure-devtestlab/Artifacts/linux-swapfile/Artifactfile.json
{
    "$schema": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/schemas/2015-01-01/dtlArtifacts.json",
    "title": "Swap File",
    "description": "Configure swap file on Linux",
    "tags": [
        "Linux"
    ],
    "iconUri": "",
    "targetOsType": "Linux",
    "parameters": {
        "size": {
            "type": "string",
            "displayName": "Size",
            "description": "The size of the swap file in bytes.  Suffixes k, m, or g correspond to KiB, MiB, or GiB. Example: 5g = 5GiB, 100m = 100MiB",
            "allowEmpty": false,
            "defaultValue": "1g"
        }
    },
    "runCommand": {
        "commandToExecute": "[concat('sh linux_swapfile.sh ', parameters('size'))]"
    }
}

=== Azure/azure-devtestlab/Artifacts/windows-install-oneget/Artifactfile.json
{
  "$schema": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/schemas/2015-01-01/dtlArtifacts.json",
  "title": "PowerShell Package Manager",
  "description": "Installs the PowerShell Package Manager for pre-Windows 10 environments",
  "tags": [
    "Windows",
    "PowerShell"
  ],
  "targetOsType": "Windows",
  "runCommand": {
    "commandToExecute": "powershell.exe -executionpolicy bypass -File installPackageManager.ps1"
  }
}

=== Azure/azure-devtestlab/Artifacts/windows-powershell/Artifactfile.json
{
  "$schema": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/schemas/2015-01-01/dtlArtifacts.json",
  "title": "PowerShell",
  "description": "Installs latest stable PowerShell version  using the Chocolatey package manager",
  "tags": [
    "Windows",
    "Fiddler"
  ],
  "iconUri": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/Artifacts/windows-powershell/PowerShellLogo.png",
  "targetOsType": "Windows",
  "runCommand": {
    "commandToExecute": "powershell.exe -ExecutionPolicy bypass -File startChocolatey.ps1 -PackageList powershell"

  }
}
