=== Azure/azure-devtestlab/schemas/2015-01-01/dtlArtifacts.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "http://schema.management.azure.com/schemas/2015-01-01/dtlArtifacts.json",
    "type": "object",
    "required": [ "title", "description", "targetOsType" ],
    "oneOf": [
        {
            "required": [ "runAzureVMExtension" ]
        },
        {
            "required": [ "runCommand" ]
        }
    ],
    "properties": {
        "title": {
            "type": "string",
            "description": "The title of your artifact."
        },
        "description": {
            "type": "string",
            "description": "The description of your artifact."
        },
        "iconUri": {
            "type": "string"
        },
        "tags": {
            "type": "array",
            "items": [
                {
                    "type": "string"
                }
            ]
        },
        "targetOsType": {
            "type": "string",
            "enum": [ "Windows", "Linux" ]
        },
        "runAzureVMExtension": {
            "type": "object",
            "properties": {
            }
        },
        "runCommand": {
            "type": "object",
            "required": [ "commandToExecute" ],
            "properties": {
                "commandToExecute": {
                    "type": "string",
                    "description": "Command to run"
                }
            },
            "additionalProperties": false
        },
        "parameters": {
            "type": "object",
            "description": "Input parameter definitions",
            "additionalProperties": {
                "$ref": "#/definitions/parameter"
            }
        }
    },
    "definitions": {
        "parameter": {
            "type": "object",
            "required": [ "type" ],
            "properties": {
                "type": {
                    "$ref": "#/definitions/parameterTypes",
                    "description": "Type of input parameter"
                },
                "controlType": {
                    "$ref": "#/definitions/controlTypes",
                    "description": "Type of UI control"
                },
                "defaultValue": {
                    "$ref": "#/definitions/parameterValueTypes",
                    "description": "Default value to be used if one is not provided"
                },
                "allowedValues": {
                    "type": "array",
                    "description": "Value can only be one of these values"
                },
                "minLength": {
                    "type": "integer",
                    "description": "Minimum number of characters that must be used"
                },
                "maxLength": {
                    "type": "integer",
                    "description": "Maximum number of characters that can be used"
                },
                "allowEmpty": {
                    "type": "boolean",
                    "description": "If an empty value is allowed, by default false"
                },
                "description": {
                    "type": "string",
                    "description": "The description of the parameter"
                },
                "displayName": {
                    "type": "string",
                    "description": "The display name of the parameter"
                }
            },
            "description": "Input parameter definitions"
        },
        "parameterTypes": {
            "enum": [
                "string",
                "securestring",
                "int",
                "bool",
                "object",
                "array"
            ]
        },
        "controlTypes": {
            "enum": [
                "textBox",
                "passwordBox",
                "fileContents"
            ]
        },
        "parameterValueTypes": {
            "type": [
                "string",
                "boolean",
                "integer",
                "number",
                "object",
                "array",
                "null"
            ]
        }
    }
}

=== Azure/azure-devtestlab/Artifacts/linux-deprovision-Ubuntu/Artifactfile.json
{
  "$schema": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/schemas/2015-01-01/dtlArtifacts.json",
  "title": "Deprovision",
  "description": "Deprovision Ubuntu Linux Vm to capture as Image.",
  "tags": [
    "Linux"
  ],
  "iconUri": "",
  "targetOsType": "Linux",
  "runCommand": {
    "commandToExecute": "['sudo /usr/sbin/waagent -force -deprovision']"
  }
}

=== Azure/azure-devtestlab/python2/artifactfile.json
{
  "$schema": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/schemas/2015-01-01/dtlArtifacts.json",
  "title": "Python 2.7",
  "description": "Installs Python 2.7 ",
  "tags": [
    "Python"
  ],
  "iconUri": "http://www.pngall.com/wp-content/uploads/2016/05/Python-Logo-Free-PNG-Image.png",
  "targetOsType": "Windows",
  "runCommand": {
    "commandToExecute": "[concat('powershell.exe -ExecutionPolicy bypass \"& ./startChocolatey.ps1 -PackageList ''', 'python2', '''\"')]"
  }
}

=== Azure/azure-devtestlab/Artifacts/windows-selenium/Artifactfile.json
{
  "$schema": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/schemas/2015-01-01/dtlArtifacts.json",
  "title": "Selenium",
  "description": "Installs Firefox, Chrome, Selenium Driver for Chrome and IE using the Chocolatey package manager (Firefox already has it)",
  "tags": [
    "Windows",
    "Firefox",
    "Chrome",
    "Selenium-Chrome",
    "Selenium-IE"
  ],
  "iconUri": "http://www.seleniumhq.org/images/selenium-logo.png",
  "targetOsType": "Windows",
  "runCommand": {
    "commandToExecute": "[concat('powershell.exe -ExecutionPolicy bypass \"& ./startChocolatey.ps1 -PackageList ', 'firefox,googlechrome,selenium-chrome-driver,selenium-ie-driver,iedriverserver', '\"')]"
  }
}

=== Azure/azure-devtestlab/wireshark/artifactfile.json
{
  "$schema": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/schemas/2015-01-01/dtlArtifacts.json",
  "title": "Wireshark",
  "description": "Installs wireshark - network trace utility",
  "tags": [
    "Wireshark",
    "PCAP",
    "Trace"
  ],
    "iconUri": "https://upload.wikimedia.org/wikipedia/commons/d/db/Wireshark_Icon.png",
  "targetOsType": "Windows",
  "runCommand": {
    "commandToExecute": "[concat('powershell.exe -ExecutionPolicy bypass \"& ./startChocolatey.ps1 -PackageList ''', 'wireshark', '''\"')]"
  }
}

=== Azure/azure-devtestlab/Artifacts/windows-vscode/Artifactfile.json
{
    "$schema": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/schemas/2015-01-01/dtlArtifacts.json",
    "title": "Visual Studio Code",
    "description": "Installs Visual Studio Code",
    "tags": [
        "Windows",
        "VSCode",
        "Visual Studio"
    ],
    "iconUri": "https://github.com/Azure/azure-devtestlab/raw/drwill/vscode/Artifacts/windows-vscode/vscode%20icon.png",
    "targetOsType": "Windows",
    "runCommand": {
        "commandToExecute": "powershell.exe -ExecutionPolicy bypass -File installVSCode.ps1"
    }
}

=== Azure/azure-devtestlab/Artifacts/windows-winrm-configuration/Artifactfile.json
{
    "$schema": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/schemas/2015-01-01/dtlArtifacts.json",
    "title": "WinRM Configuration",
    "description": "Configures WinRM with a self signed Https listner also handles firewall configuration to allow traffic on https through specified port",
    "tags": [
        "Windows",
        "WinRM"
    ],
    "iconUri": "",
    "targetOsType": "Windows",
    "parameters": {     
        "HostName": {
            "type": "string",
            "displayName": "Host DNS Name",
            "description": "The FQDN of machine or Domain, use the format *.azureregion.cloudapp.azure.com. For example *.northeurope.cloudapp.azure.com"
        },
        "Port": {
            "type": "int",
            "displayName": "Port",
            "description": "Specify the port to be used for default Https traffic.",
            "defaultValue": 5986
        }
    },
    "runCommand": {
        "commandToExecute": "[concat('powershell.exe -ExecutionPolicy bypass -File winrm-configuration-install.ps1 ', parameters('HostName'), ' ', parameters('Port'))]"
    }
}

=== Azure/azure-devtestlab/Artifacts/windows-dotnet45/Artifactfile.json
{
    "$schema": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/schemas/2015-01-01/dtlArtifacts.json",
    "title": "Microsoft .Net Framework 4.5",
    "description": "Installs Microsoft .Net Framework 4.5 using the Chocolatey package manager",
    "tags": [
        "Windows",
        "Fiddler"
    ],
    "iconUri": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/Artifacts/windows-dotnet45/dotnet.png",
    "targetOsType": "Windows",
    "runCommand": {
        "commandToExecute": "powershell.exe -executionpolicy bypass -File startChocolatey.ps1 -PackageList dotnet45"
    }
}

=== Azure/azure-devtestlab/Artifacts/linux-java/Artifactfile.json
{
    "$schema": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/schemas/2016-11-28/dtlArtifacts.json",
    "title": "JDK",
    "description": "Install Java Development Kit on Debian-based and Red Hat based distributions.",
    "tags": [
      "JDK",
      "Linux",
      "JAVA"
    ],
    "iconUri": "https://upload.wikimedia.org/wikipedia/en/thumb/3/30/Java_programming_language_logo.svg/128px-Java_programming_language_logo.svg.png",
    "targetOsType": "Linux",
	
  "runCommand": {
    "commandToExecute": "['sh linux_install_jdk.sh']"
  }
}
