=== Azure/azure-devtestlab/schemas/2015-01-01/dtlArtifacts.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "http://schema.management.azure.com/schemas/2015-01-01/dtlArtifacts.json",
    "type": "object",
    "required": [ "title", "description", "targetOsType" ],
    "oneOf": [
        {
            "required": [ "runAzureVMExtension" ]
        },
        {
            "required": [ "runCommand" ]
        }
    ],
    "properties": {
        "title": {
            "type": "string",
            "description": "The title of your artifact."
        },
        "description": {
            "type": "string",
            "description": "The description of your artifact."
        },
        "iconUri": {
            "type": "string"
        },
        "tags": {
            "type": "array",
            "items": [
                {
                    "type": "string"
                }
            ]
        },
        "targetOsType": {
            "type": "string",
            "enum": [ "Windows", "Linux" ]
        },
        "runAzureVMExtension": {
            "type": "object",
            "properties": {
            }
        },
        "runCommand": {
            "type": "object",
            "required": [ "commandToExecute" ],
            "properties": {
                "commandToExecute": {
                    "type": "string",
                    "description": "Command to run"
                }
            },
            "additionalProperties": false
        },
        "parameters": {
            "type": "object",
            "description": "Input parameter definitions",
            "additionalProperties": {
                "$ref": "#/definitions/parameter"
            }
        }
    },
    "definitions": {
        "parameter": {
            "type": "object",
            "required": [ "type" ],
            "properties": {
                "type": {
                    "$ref": "#/definitions/parameterTypes",
                    "description": "Type of input parameter"
                },
                "controlType": {
                    "$ref": "#/definitions/controlTypes",
                    "description": "Type of UI control"
                },
                "defaultValue": {
                    "$ref": "#/definitions/parameterValueTypes",
                    "description": "Default value to be used if one is not provided"
                },
                "allowedValues": {
                    "type": "array",
                    "description": "Value can only be one of these values"
                },
                "minLength": {
                    "type": "integer",
                    "description": "Minimum number of characters that must be used"
                },
                "maxLength": {
                    "type": "integer",
                    "description": "Maximum number of characters that can be used"
                },
                "allowEmpty": {
                    "type": "boolean",
                    "description": "If an empty value is allowed, by default false"
                },
                "description": {
                    "type": "string",
                    "description": "The description of the parameter"
                },
                "displayName": {
                    "type": "string",
                    "description": "The display name of the parameter"
                }
            },
            "description": "Input parameter definitions"
        },
        "parameterTypes": {
            "enum": [
                "string",
                "securestring",
                "int",
                "bool",
                "object",
                "array"
            ]
        },
        "controlTypes": {
            "enum": [
                "textBox",
                "passwordBox",
                "fileContents"
            ]
        },
        "parameterValueTypes": {
            "type": [
                "string",
                "boolean",
                "integer",
                "number",
                "object",
                "array",
                "null"
            ]
        }
    }
}

=== Azure/azure-devtestlab/Artifacts/windows-vsts-build-agent/Artifactfile.json
{
    "$schema": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/schemas/2015-01-01/dtlArtifacts.json",
    "title": "VSTS Build Agent",
    "description": "Downloads and installs the build agent, registers with the specified Visual Studio Team Services account, and adds the VM to the specified agent pool.",
    "tags": [
        "VSTS",
        "Build",
        "CI",
        "Windows"
    ],
    "iconUri": "",
    "targetOsType": "Windows",
    "parameters": {
        "vstsAccount": {
            "type": "string",
            "displayName": "VSTS Account",
            "description": "The name of the VSTS account to add the build agent to. This is the value of in your VSTS URL: e.g. 'myaccount' in https://myaccount.visualstudio.com."
        },
        "vstsUser": {
            "type": "string",
            "displayName": "VSTS User",
            "description": "User login name for a user with permissions to add build agents."
        },
        "vstsPassword": {
            "type": "securestring",
            "displayName": "VSTS Password",
            "description": "Password for the user with permissions to add build agents."
        },
        "agentName": {
            "type": "string",
            "displayName": "Agent Name",
            "description": "The name to give to the agent as seen by VSTS."
        },
        "poolName": {
            "type": "string",
            "displayName": "Agent Pool",
            "description": "The agent pool this build agent should be added to."
        }
    },
    "runCommand": {
        "commandToExecute": "[concat('powershell.exe -ExecutionPolicy bypass -File vsts-agent-install.ps1 ', parameters('vstsAccount'), ' ', parameters('vstsUser'), ' ', parameters('vstsPassword'), ' ', parameters('agentName'), ' ', parameters('poolName'))]"
    }
}

=== Azure/azure-devtestlab/Artifacts/windows-sharepoint2013A/Artifactfile.json
{
  "$schema": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/schemas/2015-01-01/dtlArtifacts.json",
  "title": "SharePoint Server 2013 (1) Prerequisites installer",
  "description": "Installs SharePoint Server 2013 Prerequisites.",
  "tags": [
    "Windows"
  ],
  "iconUri": "https://i-msdn.sec.s-msft.com/dynimg/IC792065.jpg",
  "targetOsType": "Windows",
  "parameters": {
    "downloadUrl": {
      "type": "string",
      "displayName": "Download URL for SharePoint",
      "description": "The download URL for SharePoint 2013.",
      "defaultValue": "https://download.microsoft.com/download/6/E/3/6E3A0B03-F782-4493-950B-B106A1854DE1/sharepoint.exe"
    }
  },
  "runCommand": {
    "commandToExecute": "[concat('powershell.exe -ExecutionPolicy bypass -File SharePoint2013SP1P1.ps1', ' -downloadUrl ', parameters('downloadUrl'))]"
  }
}

=== Azure/azure-devtestlab/Artifacts/windows-slack/Artifactfile.json
{
    "$schema": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/schemas/2016-11-28/dtlArtifacts.json",
    "title": "Slack",
    "description": "Installs Slack using the Chocolatey package manager",
    "tags": [
        "Windows",
        "Slack"
    ],
    "iconUri": "https://chocolatey.org/content/packageimages/slack.1.0.0.png",
    "targetOsType": "Windows",
    "parameters": {
        "installUsername": {
            "type": "string",
            "displayName": "Install User Name",
            "description": "The local user name for which the artifact will be installed"
        },
        "installPassword": {
            "type": "securestring",
            "displayName": "Install Password",
            "description": "User password"
        }
    },
    "runCommand": {
        "commandToExecute": "[concat('powershell.exe -ExecutionPolicy bypass \"& ./startChocolatey.ps1 -PackageList ', 'slack', ' -UserName ', parameters('installUsername'), ' -Password ', parameters('installPassword'), '\"')]"
    }
}

=== Azure/azure-devtestlab/Artifacts/windows-git/Artifactfile.json
{
  "$schema": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/schemas/2015-01-01/dtlArtifacts.json",
  "title": "git",
  "description": "Installs git using the Chocolatey package manager",
  "tags": [
    "Windows",
    "Git"
  ],
  "iconUri": "https://cdn.rawgit.com/ferventcoder/chocolatey-packages/02c21bebe5abb495a56747cbb9b4b5415c933fc0/icons/git.svg",
  "targetOsType": "Windows",
  "runCommand": {
    "commandToExecute": "powershell.exe -ExecutionPolicy bypass -File startChocolatey.ps1 -PackageList git.install"

  }
}

=== Azure/azure-devtestlab/Artifacts/windows-restart/Artifactfile.json
{
  "$schema": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/schemas/2015-01-01/dtlArtifacts.json",
  "title": "Restart machine",
  "description": "Restarts the machine",
  "tags": [
    "Windows"
  ],
  "iconUri": "",
  "targetOsType": "Windows",
  "parameters": {
  },
  "runCommand": {
    "commandToExecute": "['powershell.exe -executionpolicy bypass -File Restart.ps1']"
  }
}

=== Azure/azure-devtestlab/Artifacts/linux-yum-package/Artifactfile.json
{
    "$schema": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/schemas/2015-01-01/dtlArtifacts.json",
    "title": "Yum",
    "description": "Install packages on a Linux Azure DevTest Lab VM via YUM",
    "tags": [
        "Package Management",
        "Yum",
        "install",
        "Linux"
    ],
    "iconUri": "http://fedoraproject.org/w/uploads/7/77/Echo-package-48px.png",
    "targetOsType": "Linux",
    "parameters": {
        "packages": {
            "type": "string",
            "displayName": "Packages",
            "allowEmpty": false,
            "description": "The packages to install on the VM, separated by spaces. All of the package declarations supported by yum are supported here as well, see http://man7.org/linux/man-pages/man8/yum.8.html for an in-depth look at the package specifications available."
        },
        "update": {
            "type": "string",
            "displayName": "Run Update First",
            "defaultValue": "true",
            "description": "Run yum update prior to running the full install command. Allowed values are 'true' and 'false', or blank (which will evaluate to false). Note that no additional options are passed to the update command."
        },
        "options": {
            "type": "string",
            "displayName": "Additional Options",
            "allowEmpty": true,
            "description": "Any additional options to pass to the yum command line. These options will precede the install command when executed. Please see http://man7.org/linux/man-pages/man8/yum.8.html for an in-depth look at the options available. Note that --assumeyes and --quiet are always passed automatically."
        }
    },
    "runCommand": {
        "commandToExecute": "[concat('bash linux-yum-package.sh', ' --update ', parameters('update'), ' --packages ', parameters('packages'), ' --options ', parameters('options'))]"
    }
}

=== Azure/azure-devtestlab/Artifacts/windows-addUser/Artifactfile.json
{
  "$schema": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/schemas/2015-01-01/dtlArtifacts.json",
  "title": "Add admin user",
  "description": "Creates a new admin user and adds it to the administrator group",
  "tags": [
    "Windows"
  ],
  "iconUri": "",
  "targetOsType": "Windows",
  "parameters": {
    "Username": {
      "type": "string",
      "displayName": "Username",
      "description": "Username",
      "defaultValue": ""
    },
    "Password": {
      "type": "securestring",
      "displayName": "Password",
      "description": "Password",
      "defaultValue": ""
    }
  },
  "runCommand": {
    "commandToExecute": "[concat('powershell.exe -executionpolicy bypass -File CreateAdminUser.ps1 ', parameters('Username'), ' ', parameters('Password'))]"
  }
}

=== Azure/azure-devtestlab/Artifacts/windows-adobe-flex-sdk/Artifactfile.json
{
    "$schema": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/schemas/2016-11-28/dtlArtifacts.json",
    "title": "Adobe Flex SDK",
    "description": "Installs Adobe Flex SDK, EULA: http://www.adobe.com/products/eulas/#flex_sdk",
    "tags": [
        "Windows",
        "Adobe",
        "Flex"
    ],
    "iconUri": "https://github.com/Azure/azure-devtestlab/raw/master/Artifacts/windows-vscode/flex%20icon.png",
    "targetOsType": "Windows",
    "runCommand": {
        "commandToExecute": "powershell.exe -ExecutionPolicy bypass -File installAdobeFlex.ps1"
    }
}
